# Generated by Django 3.0.6 on 2020-08-19 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cin', models.CharField(max_length=12)),
                ('nom_complet', models.CharField(max_length=256)),
                ('sexe', models.CharField(max_length=10)),
                ('adresse', models.CharField(max_length=256)),
                ('tel', models.CharField(max_length=20)),
                ('mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('dte_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_rv', models.DateField()),
                ('heure_rv', models.TimeField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rvs', to='doc_budy.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Ordonance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_ord', models.DateField()),
                ('heure_ord', models.TimeField()),
                ('prescription', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordonances', to='doc_budy.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Consulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_consultation', models.DateField()),
                ('heure_consultation', models.TimeField()),
                ('type_consultation', models.CharField(max_length=50)),
                ('prix', models.FloatField()),
                ('symptome', models.CharField(max_length=256)),
                ('observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations', to='doc_budy.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dte_certf', models.DateField()),
                ('heure_certf', models.TimeField()),
                ('observation', models.TextField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificats', to='doc_budy.Patient')),
            ],
        ),
    ]
