# Generated by Django 3.0.6 on 2020-08-19 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_budy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(choices=[('F', 'Female'), ('M', 'Male')], max_length=1),
        ),
    ]
