# Generated by Django 3.0.6 on 2020-08-19 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_budy', '0002_auto_20200819_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='sexe',
            field=models.CharField(max_length=1),
        ),
    ]
